version: '3.9'
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
     - "/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf"
     - "/mosquitto/mosquitto_data:/mosquitto/data"
     - "/mosquitto/mosquitto_log:/mosquitto/log"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  console:
    container_name: rut_pi_console
    restart: always
    build: rut_pi_console\.
